inrupt/solid-react-components

src/lib/components/ProviderLogin/provider-login.container.js
Remove error message on ProviderLogin component when the user selects a provider.
=> remove error message when user select a provider

CHANGELOG.md, src/demo/App.js, src/lib/components/Uploader/uploader.component.js
Added functionality to rename files uploaded on POD.
Fixed Image Loaded hangs after Multiple Loads.
=> fixed uploader issue

src/lib/components/Uploader/uploader.component.js
Fixed https://github.com/Inrupt-inc/solid-react-components/issues/45 issue.
=> fixed package version

src/lib/components/ShexFormBuilder/shex-form-builder.component.js, src/lib/hooks/useShex.js
Removed warning message after the user saves the field.
Added language support on form validation
=> Releases updates

package-lock.json, src/lib/components/ShexForm/children/DropDownField/dropdown-field.component.js, src/lib/components/ShexForm/children/Field/field.component.js, src/lib/components/ShexForm/children/InputField/input-field.component.js, src/lib/components/ShexForm/children/InputField/styled.component.js, src/lib/hooks/useShex.js
On save field data the edit field widget is disabled and shown with a grey background,
If the edited field value is successfully autosaved, the edit field widget is enabled and the background reset.
Video about the new feature: http://recordit.co/7Lirsrlm5A
=> Added functionality to disabled input and dropdown on save

package-lock.json, package.json, src/lib/classes/app-permissions.js, src/lib/classes/index.js, src/lib/index.js
Functionality to get app permissions on the pod: http://recordit.co/z5njHGZZuF
=> add app permission functionality

src/lib/components/FormModel/children/Form/UI/DateTimePicker/date-time-picker.component.js, src/lib/utils/index.js
This PR includes:
- Time and datetime pickers display the full localized time
- Data is now saved as a UTC standard time
- Datetime pickers will correctly override any offset if a minValue or maxValue exist in the form model.
=> Update datepicker displays and saved data format

src/demo/App.js, src/lib/components/FormModel/children/Form/UI/TextArea/text-area.component.js, src/lib/components/FormModel/children/Form/UI/TextArea/text-area.styles.js
- display the form element in the form renderer
- fix styles
- display label value
- bind current value
=> changes in multiline textfield:

src/lib/components/FormModel/children/Form/UI/ColorPicker/color-picker.component.js, src/lib/components/FormModel/children/Form/UI/ColorPicker/color-picker.styles.js, src/lib/components/FormModel/children/Form/UI/ColorPicker/index.js, src/lib/components/FormModel/children/Form/UI/index.js, src/lib/components/FormModel/children/Form/UI/ui-mapping.js
In this PR: 
- Implement a color picker based on `react-color`
=> Color picker

src/lib/components/FormModel/children/Form/UI/Decimal/decimal.component.js, src/lib/components/FormModel/children/Form/UI/Float/float.component.js
Fixing input lenght- Float Decimal
=> Fixing the input length

src/lib/components/FormModel/children/Form/UI/Input/input.component.js, src/lib/components/FormModel/children/Form/UI/ui-mapping.js
Adding the PhoneField and EmailField to the renderer. Adding the pattern to the input.
=> PhoneField and EmailField renderer and pattern

src/lib/classes/access-control-list.js, src/lib/constants/index.js
Fixes https://github.com/inrupt/solid-react-components/issues/171
=> Use correct type predicate.

src/lib/components/FormModel/children/Viewer/UI/SingleLine/single-line.style.js
Remove bold attr from all SingleLine components in view mode.
=> Remove bold attr from all SingleLine components in view mode

src/lib/components/FormModel/children/Form/UI/CheckBox/check-box.component.js
Now the component will wait for the form object to be properly updated before trying to save the value.
=> Update component to properly save and fetch values

src/lib/components/FormModel/children/Form/UI/Email/email.component.js, src/lib/components/FormModel/children/Form/UI/Email/email.test.js, src/lib/components/FormModel/children/Form/UI/Email/index.js, src/lib/components/FormModel/children/Form/UI/Phone/index.js, src/lib/components/FormModel/children/Form/UI/Phone/phone.component.js, src/lib/components/FormModel/children/Form/UI/Phone/phone.test.js, src/lib/components/FormModel/children/Form/UI/index.js, src/lib/components/FormModel/children/Form/UI/ui-mapping.js
Add two new UI components one for Email and another one for Phone.
Remove the pattern for the general Input.
=> Fixing issue with pattern

README.md
=> Fix Solid website URL

package-lock.json, package.json, src/demo/App.js, src/lib/components/FormModel/children/Form/UI/Classifier/classifier.component.js, src/lib/components/FormModel/children/Multiple/multiple.component.js, src/lib/components/FormModel/children/Viewer/UI/MultipleViewer/multiple-viewer.component.js, src/lib/components/FormModel/children/Viewer/viewer.component.js, src/lib/components/FormModel/form-model.component.js
Code correcting the display and value fetching of multiples and groups for the Viewer
=> Updating viewer code to use Multiple and Groups correctly

package.json, src/demo/App.js, src/lib/components/FormModel/form-model.component.js
App.js was also updated to include new language and different form model - App.js is a developer playground and not part of the bundled components.
=> Updating form renderer to pass through language code

src/lib/components/FormModel/children/Form/UI/CheckBox/check-box.component.js, src/lib/components/FormModel/children/Form/UI/Decimal/decimal.component.js, src/lib/components/FormModel/children/Form/UI/Float/float.component.js, src/lib/components/FormModel/children/Form/UI/Integer/integer.component.js
* Added missing classes passed in by parent
* Added input wrapper with some basic formatting CSS
=> Updating number and checkbox field structure and style

package-lock.json, package.json, src/lib/classes/notification.js, src/lib/utils/shex.js
* Upgraded to latest shexjs/core version
* Revamped the shexjs code so it is no longer looping over each file sequentially
* Made updates so the shex code returns a list of valid data's quads
* Updated the parsing code so it no longer re-fetches the code
* Renamed solidLDFlex to data so it is more in line with code samples of ldflex package
=> Refactor the notification validation, retrieval
